### ISSUE TITLE
Query times

### ISSUE THREAD

**Issue by itay** [datasapiens/alluxio-s3-costs-test#1]
Great writeup on the Alluxio blog, and very interested results. I'm curious - do you happen to have the query time comparisons as well? It would be very interesting to see how those differed between the two setups, as you mentioned the Alluxio ones were shorter. Given that with TPC-DS, some of the queries are much more compute bound than IO-bound, it would be insightful to see the differences.

**Comment by jpohanka** [comment]
@itay Thank you very much! Regarding the speed-up, we didn't measure this in our example. However we trully did observe the speed-up for the TPC-DS suite queries, as well as for the queries running in client's internal reports. The speed-up may vary from query to query, and also there were cases when the query performance god slightly worse (decrease say by 5%). But in the vast majority, there was a visible speed-up, especially for queries, which require a higher number of stages in Presto.

There are few articles that measure directly the difference with and without Alluxio, i.e. this white paper directly from them: https://www.alluxio.io/resources/whitepapers/zero-copy-hybrid-cloud-for-data-analytics-strategy-architecture-and-benchmark-report/
